### ISSUE TITLE
Refactor: Create database connection without Laravel's app() helper

### ISSUE THREAD

**Issue by minthemiddle** [calebporzio/bear-sync#2]
- It would be great if you could *bear_sync* without Laravel
- The only problem so far is `app()` (BearNote.php, l.54) which throws an `undefined function()`
- One idea on the how can be found in [this gist](https://gist.github.com/craighooghiem/9979298)
- (I will try to create a PR for this)

**Comment by calebporzio** [comment]
Yeah, that should do, I'd like to resolve ConnectionFactory out of the container for Laravel apps, so maybe a conditional that checks if "app()" is defined and uses the strategy you referenced if it's not? Looks good to me though.
