### ISSUE TITLE
Incorrect pivot table in BearTag model

### ISSUE THREAD

**Issue by joedixon** [calebporzio/bear-sync#4]
The `BearTag` model uses `Z_6TAGS` as the pivot table between tags and notes.

However, in my Bear notes, the pivot table is called `Z_7TAGS`. The table columns are also named differently:

`Z_7NOTES` vs `Z_6NOTES `
`Z_14TAGS` vs `Z_6NOTES `

Not sure why they differ. If it helps, I'm on version 1.7.7.

**Comment by denniseilander** [comment]
@joedixon 
I had the same issue. Just fixed it with a quick fix:

Create a new `App\Tag` model and overwrite the `notes()` method.  
For example:

```php
use BearSync\BearTag;

class Tag extends BearTag
{
    public function notes()
    {
        return $this->:belongsToMany(BearNote::class, 'Z_7TAGS', 'Z_14TAGS', 'Z_7NOTES');
    }
}
```
I think Bear uses different column/table names per version. 

I'm trying to find a dynamic way to auto detect the column names. But not sure yet how to fix it without overriding the method

**### UPDATE:**
Using the above quick solution will break the connection of your own database, when you are using it.

This works fine:
`App\BearNote.php`
```php
use BearSync\BearNote as Note;
use BearSync\BearTag as Tag;

class BearNote extends Note
{
    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'Z_7TAGS', 'Z_7NOTES', 'Z_14TAGS');
    }
}
```

`App\BearTag.php`
```php
use BearSync\BearNote as Note;
use BearSync\BearTag as Tag;

class BearTag extends Tag
{
    public function notes()
    {
        return $this->belongsToMany(Note::class, 'Z_7TAGS', 'Z_14TAGS', 'Z_7NOTES');
    }
}
```

**Comment by joedixon** [comment]
@calebporzio, I'm digging some digging to see if I can get any more info from the database to make a dymanic solution.

Can you do me a favour and look at the values in the `Z_ENT` field of your `ZSFNOTE` and `ZSFNOTETAG` tables?

**Comment by calebporzio** [comment]
Sure thing! (thanks for looking into this!)

![image](https://user-images.githubusercontent.com/3670578/72081083-dc0fe300-32cb-11ea-8c04-0f1d5622994b.png)
![image](https://user-images.githubusercontent.com/3670578/72081101-e29e5a80-32cb-11ea-9f3b-c6dd68f916b6.png)

**Comment by denniseilander** [comment]
@joedixon @calebporzio I've tried to write a fix for this issue, with success...

I have extended the `UsesBearsDatabaseConnection.php` with 2 functions to retrieve the right **table** and **columns**

Then the function can be called in the `BearNote` and `BearTag` models with a regex to filter the right table/columnames.

For example, the  `tags()` relation in the BearNote model has to be updated:

```php
// Before
public function tags()
{
    return $this->belongsToMany(BearTag::class, 'Z_6TAGS', 'Z_6NOTES', 'Z_13TAGS');
}
```

```php
// After
public function tags()
{
    return $this->belongsToMany(BearTag::class, static::getTagsTable(), static::getColumn('Z_[0-9]+NOTES'), static::getColumn('Z_[0-9]+TAGS'));
}
```

There is no configuration needed for the user. 
I tested it by changing the column names of the tables and still able to retrieve the notes from Bear.

I make use of the `SQLite3` class to select the raw data from the sqlite database. I couldn't retrieve that data using another way..

I can share the code with you/create a pull request if you want?
But I think you have to check the code and maybe refactor it.

Please let me know.

**Comment by joedixon** [comment]
Hi @denniseilander, I put a PR up before seeing this comment. I used a similar approach, but got the data for generating the table and column names from a different place.

Let me know what you think https://github.com/calebporzio/bear-sync/pull/5

**Comment by denniseilander** [comment]
@joedixon sorry for the late response, but your code is much cleaner and a better way to fix this problem. Thanks for fixing, did learn something today again.
